# System of Linear Equations with a Unique Solution, Matrix Inverse and the Determinant

The goal of this homework is to learn how to solve systems of linear equations and to be able to compute the determinant and the inverse of an invertible matrix.

**After this assignment you will be able to:**
- Use `NumPy` package to set up the arrays corresponding to the system of linear equations.
- Evaluate the determinant of a matrix and find the solution of the system with `NumPy` linear algebra package.
- Perform row reduction to bring matrix into row echelon form
- Find the solution for the system of linear equations using row reduced approach.
- Compute the inverse of a matrix with `Numpy` linear algebra package and using row reduction approach.

## 1. Solving System of Linear Equations

### 1.1 Row Reduction approach


Solve the following system of linear equations using the reduction method (as mentioned in the week 2 lab):
$$\begin{cases}
x + 2y - 3z + 4w = 12, \\ 2x + 2y - 2z + 3w = 10, \\ y + z = -1, \\ x - y + z - 2w = -4 \end{cases}\tag{1}$$


In [47]:
import numpy as np

A = np.array([
        [1, 2, -3, 4],
        [2, 2, -2, 3],
        [0, 1, 1, 0],
        [1, -1, 1, -2]
    ])

b = np.array([12, 10, -1, -4])
A_system = np.hstack((A, b.reshape(4,1)))
print(A_system)

[[ 1  2 -3  4 12]
 [ 2  2 -2  3 10]
 [ 0  1  1  0 -1]
 [ 1 -1  1 -2 -4]]


In [48]:
def AddRows(M, row_a, row_b, scalar):
  copyM = M.copy()
  copyM[row_a] =  scalar * copyM[row_b] + copyM[row_a]
  return copyM

def MultiplyRows(M, row, scalar):
  copyM = M.copy()
  copyM[row] *= scalar
  return copyM

def SwapRows(M, row_a, row_b):
  copyM = M.copy()
  copyM[[row_a, row_b]] = copyM[[row_b, row_a]]
  return copyM

In [49]:
A_aug = AddRows(A_system, 1, 3, -2)
A_aug = AddRows(A_aug, 1, 2, -4)
A_aug = AddRows(A_aug, 0, 2, -2)
A_aug = AddRows(A_aug, 3, 0, -1)
A_aug = AddRows(A_aug, 3, 2, 1)
A_aug = AddRows(A_aug, 1, 3, 1)
A_aug = AddRows(A_aug, 2, 1, 1)
A_aug = AddRows(A_aug, 3, 1, 7)
A_aug = AddRows(A_aug, 2, 3, -1)
A_aug = AddRows(A_aug, 1, 3, -1)
A_aug = MultiplyRows(A_aug, 1, -1)
A_aug = AddRows(A_aug, 0, 1, 5)
A_aug = AddRows(A_aug, 0, 3, -4)
A_aug = SwapRows(A_aug, 1, 2)


In [50]:
A_aug

array([[ 1,  0,  0,  0,  1],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  1,  0, -1],
       [ 0,  0,  0,  1,  2]])

### 1.2 `Numpy` linear algebra package
Solve the above system of linear equations using the `numpy.linalg` package.

In [55]:
np.linalg.solve(A, b)

array([ 1., -0., -1.,  2.])

## 2. Determinant
### 2.1 Compute the determinant of matrix $A$ using the `numpy.linalg` package:

$$ \begin{align}
  \textbf{A}  = \begin{bmatrix}
1 & 0 & -2\\
3 & 1 & -2\\
-5 & -1 & 9
\end{bmatrix}
  \end{align}
  $$

In [56]:
A = np.array([
        [1, 0, -2],
        [3, 1, -2],
        [-5, -1, 9]
    ])
np.linalg.det(A)

3.000000000000001

### 2.2 Is the above matrix invertible? Why?

Answer here: Yes, since it passes the test that the determinant is a non-zero value.

# 3. Matrix Inverse
### 3.1 Compute the inverse of non-singular matrix $B$ using row reduction
$$ \begin{align}
  \textbf{B}  = \begin{bmatrix}
1 & 2 & 1\\
4 & 4 & 5\\
6 & 7 & 7
\end{bmatrix}
  \end{align}
  $$

In [57]:
B = np.array([
        [1, 2, 1],
        [4, 4, 5],
        [6, 7, 7]
    ])
B_aug = np.hstack((B, np.identity(3)))
B_aug

array([[1., 2., 1., 1., 0., 0.],
       [4., 4., 5., 0., 1., 0.],
       [6., 7., 7., 0., 0., 1.]])

In [68]:
B_aug = AddRows(B_aug, 1, 0, -4)
B_aug = AddRows(B_aug, 2, 0, -6)
B_aug = AddRows(B_aug, 1, 2, -1)
B_aug = AddRows(B_aug, 2, 1, 5)
B_aug = AddRows(B_aug, 0, 1, -2)
B_aug = AddRows(B_aug, 0, 2, -1)


In [69]:
B_aug

array([[ 1.,  0.,  0., -7., -7.,  6.],
       [ 0.,  1.,  0.,  2.,  1., -1.],
       [ 0.,  0.,  1.,  4.,  5., -4.]])

In [70]:
B_inv = (np.hsplit(B_aug, 2))[1]
B_inv

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])

### 3.2 Compute the inverse matrix $B$ using the `numpy.linalg` package.

In [71]:
np.linalg.inv(B)

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])