# 1. Vectors Operations

In the first part of this homework we will use Python and `NumPy` functions to perform main vector operations:
- scalar multiplication
- sum of vectors
- dot product

## Packages

Import the `NumPy` package to access its functions.

In [17]:
import numpy as np

<a name='1.1'></a>
## 1.1 - Scalar Multiplication

Write a function named `ScalarMultiplication` that gets as an input a numpy array $v$ representing a vector and a scalar $\alpha$ and returns the $\alpha v$. Hint: In Python you can perform this operation with a $*$ operator. Replace `None` with your solution.

In [18]:
def ScalarMultiplication(v, a):
  return v*a

<a name='1.2'></a>
## 1.2 - Vectors Addition with Loops

Write a function named `AddLoop` that gets as an input two numpy arrays $v$ and $w$ representing two vectors and returns the $v + w$ using a for loop. For simplicity, assume the vectors $v$ and $w$ have the same length. Replace `None` with your solution.

In [19]:
def AddLoop(v,w):
  result=[]
  for i in range(len(v)):
    result.append(v[i]+w[i])
  return result


In [20]:
print(AddLoop([1,2,3], [5,1,8]))

[6, 3, 11]


<a name='1.3'></a>
## 1.3 - Vectors Addition with `Numpy` package

Write a function named `Add` that gets as an input two numpy arrays $v$ and $w$ representing two vectors and returns the $v + w$ using the `Numpy` package. For simplicity, assume the vectors $v$ and $w$ have the same length. Replace `None` with your solution.

In [21]:
def Add(v,w):
  return np.add(v,w)

In [22]:
print(Add([1,2,3],[5,1,8]))

[ 6  3 11]


<a name='1.4'></a>
## 1.4 - Dot Product with Loops

Write a function named `DotLoop` that gets as an input two numpy arrays $v$ and $w$ representing two vectors and returns the dot product between $v$ and $w$ using a for loop. For simplicity, assume the vectors $v$ and $w$ have the same length. Replace `None` with your solution.

In [23]:
def DotLoop(v,w):
  result=0
  # dot product: v1*w1 + v2*w2 +v3*w3 ...
  for i in range(len(v)):
    result += v[i]*w[i]
  return result

In [24]:
print(DotLoop(np.array([1,4,7]), np.array([3,6,2])))

41


<a name='1.5'></a>
## 1.5 - Dot Product

Write a function named `Dot` that gets as an input two numpy arrays $v$ and $w$ representing two vectors and returns the  dot product between $v$ and $w$ using the `Numpy` package. For simplicity, assume the vectors $v$ and $w$ have the same length. Replace `None` with your solution.

In [25]:
def Dot(v,w):
  return np.dot(v,w)

In [26]:
print(Dot(np.array([1,4,7]), np.array([3,6,2])))


41


# 2. Matrix Operations

In the second part of this homework we will use Python and NumPy functions to perform main matrix operations:

- sum of matrices
- matrix multiplication

### 2.1 Addition

Write a function named `AddMatrices` that gets as an input two numpy arrays $A$ and $B$ representing two matrices and returns the sum of $A$ and $B$. Replace `None` with your solution.

In [27]:
def AddMatrices(A,B):
  return np.add(A, B)

In [28]:
A = np.array([[1,2,3],[2,3,4]])
B = np.array([[0,1,0],[1,1,5]])
print(AddMatrices(A,B))

[[1 3 3]
 [3 4 9]]


### 2.2 Matrix Multiplication with Loops

Write a function named `MultiplyMatricesLoop` that gets as an input two numpy arrays $A$ and $B$ representing two matrices and returns the product of $A$ and $B$ using for or while loops. Make sure to check whether this operation can be performed. Return $-1$ if we cannot multiply $A$ with $B$. Replace `None` with your solution.

In [29]:
def MultiplyMatricesLoop(A,B):
  if A.shape[1] != B.shape[0]:
    return -1
  result = np.zeros((A.shape[0], B.shape[1]))
  for i in range(A.shape[0]):
      for j in range(B.shape[1]): 
          for k in range(A.shape[1]):  
              result[i][j] += A[i][k] * B[k][j]
  return result

In [30]:
# working example
A=np.array([[1,2,3],[1,0,1],[3,4,1]])
B=np.array([[2,4,2],[3,1,1],[0,1,2]])
print(MultiplyMatricesLoop(A,B))

# example with diff dimensions, returns -1
C=np.array([[1,2,3],[1,0,1],[3,4,1]])
D=np.array([[2,4,2],[3,1,1]])
print(MultiplyMatricesLoop(C,D))

[[ 8.  9. 10.]
 [ 2.  5.  4.]
 [18. 17. 12.]]
-1


### 2.2 Matrix Multiplication

Write a function named `MultiplyMatrices` that gets as an input two numpy arrays $A$ and $B$ representing two matrices and returns the product of $A$ and $B$ using the `Numpy` package. Make sure to check whether this operation can be performed. Return $-1$ if we cannot multiply $A$ with $B$. Replace `None` with your solution.

In [31]:
def MultiplyMatrices(A,B):
  if A.shape[1] != B.shape[0]:
    return -1
  return A*B

In [32]:
# working example
A=np.array([[1,2,3],[1,0,1],[3,4,1]])
B=np.array([[2,4,2],[3,1,1],[0,1,2]])
print(MultiplyMatrices(A,B))

# example with diff dimensions, returns -1
C=np.array([[1,2,3],[1,0,1],[3,4,1]])
D=np.array([[2,4,2],[3,1,1]])
print(MultiplyMatrices(C,D))

[[2 8 6]
 [3 0 1]
 [0 4 2]]
-1
